apiVersion: v1
kind: Service
metadata:
  name: {{ include "swiftqueue.fullname" . }}
  labels:
    {{- include "swiftqueue.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: 30007
  selector:
    {{- include "swiftqueue.selectorLabels" . | nindent 4 }}
