name: Build & Deploy Master Branch

# Run this workflow every time a new commit pushed to the repository
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - synchronize
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile
        run: mvn compile
      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
        continue-on-error: true
      - name: Test
        run: mvn test
      - name: Package
        run: mvn package
      - name: Prepare Artifact
        if: github.ref == 'refs/heads/master'
        run: mkdir -p staging/target && cp -r target/* staging/target
      - name: Upload Artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
#        if: github.ref == 'refs/heads/master'
        with:
          name: app-artifact
          path: staging
  Docker:
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: app-artifact
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push with RevisionId tag
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: swiftqueuetest/swiftqueue:${{ github.sha }},swiftqueuetest/swiftqueue:latest
          context: target/
          file: target/Dockerfile
  Deploy:
    runs-on: ubuntu-latest
    needs: Docker
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to Production
        uses: steebchen/kubectl@master
        env:
          # A base-64 representation of ~/.kube/config file
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image deployment/swiftqueue swiftqueue=swiftqueuetest/swiftqueue:${{ github.sha }} -n swiftqueue
